# Generated by Django 5.0.6 on 2024-05-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.FloatField(unique=True)),
                ('headline', models.CharField(max_length=30, unique=True)),
                ('image', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('context', models.TextField()),
                ('date_published', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
            ],
        ),
    ]
