version: '3.8'

services:
  cache:
    image: redis:6.0.9
    container_name: nicetomeetyou-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server
    networks:
      - redis-network

volumes:
  redis-data:

networks:
  redis-network:
