# Generated by Django 5.0 on 2024-05-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_author_name_news_report_datetime_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(default='Missing', unique=True),
        ),
    ]
